import type { Incident, Route } from "./types";

// VIT Bhopal University, Kothri Kalan, Sehore, Madhya Pradesh
export const CAMPUS_CENTER = { lat: 23.0796, lng: 76.8475 };

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "inc-001",
    title: "Suspicious Person Near Library",
    description: "Unknown individual loitering near the north entrance of the main library for over an hour.",
    category: "suspicious_activity",
    severity: "medium",
    lat: 23.0802,
    lng: 76.8468,
    location: "Central Library, VIT Bhopal",
    timestamp: new Date(Date.now() - 1000 * 60 * 25),
    status: "approved",
    reportedBy: "student_anon_42",
  },
  {
    id: "inc-002",
    title: "Bike Theft at Dorm C",
    description: "Bicycle was stolen from the rack outside Dorm C building. Lock was cut.",
    category: "theft",
    severity: "high",
    lat: 23.0791,
    lng: 76.8489,
    location: "Men's Hostel Block C, VIT Bhopal",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    status: "approved",
    reportedBy: "student_anon_17",
  },
  {
    id: "inc-003",
    title: "Broken Street Light",
    description: "Street light near the science building has been out for two nights. Area is very dark.",
    category: "infrastructure",
    severity: "low",
    lat: 23.0785,
    lng: 76.8461,
    location: "Tech Tower, East Corridor, VIT Bhopal",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
    status: "approved",
    reportedBy: "student_anon_88",
  },
  {
    id: "inc-004",
    title: "Verbal Harassment Reported",
    description: "Student reported being verbally harassed near the campus cafe.",
    category: "harassment",
    severity: "high",
    lat: 23.0799,
    lng: 76.8479,
    location: "Food Court, VIT Bhopal",
    timestamp: new Date(Date.now() - 1000 * 60 * 40),
    status: "approved",
    reportedBy: "student_anon_55",
  },
  {
    id: "inc-005",
    title: "Medical Emergency - Student Fainted",
    description: "Student collapsed near the gym entrance. Campus health was called.",
    category: "medical",
    severity: "critical",
    lat: 23.0808,
    lng: 76.8472,
    location: "Sports Complex, VIT Bhopal",
    timestamp: new Date(Date.now() - 1000 * 60 * 10),
    status: "pending",
    reportedBy: "student_anon_31",
  },
  {
    id: "inc-006",
    title: "Suspicious Package",
    description: "Unattended bag left near the admin building for over 30 minutes.",
    category: "suspicious_activity",
    severity: "high",
    lat: 23.0788,
    lng: 76.8483,
    location: "Administrative Block, VIT Bhopal",
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    status: "pending",
    reportedBy: "student_anon_9",
  },
];

export const MOCK_ROUTES: Route[] = [
  {
    id: "route-001",
    name: "Safe Route via Main Path",
    points: [
      { lat: 23.0802, lng: 76.8468, label: "Library" },
      { lat: 23.0799, lng: 76.8472, label: "Food Court" },
      { lat: 23.0793, lng: 76.8476, label: "Admin Block" },
      { lat: 23.0787, lng: 76.8482, label: "Main Gate" },
    ],
    distance: "0.6 km",
    duration: "8 min",
    safetyScore: 92,
    alerts: [],
  },
  {
    id: "route-002",
    name: "Alternate via Hostel Road",
    points: [
      { lat: 23.0802, lng: 76.8468, label: "Library" },
      { lat: 23.0808, lng: 76.8472, label: "Sports Complex" },
      { lat: 23.0810, lng: 76.8480, label: "Boys Hostel" },
      { lat: 23.0787, lng: 76.8482, label: "Main Gate" },
    ],
    distance: "0.9 km",
    duration: "12 min",
    safetyScore: 74,
    alerts: ["inc-002"],
  },
];
