spring:
  application:
    name: campus-guardian-backend

  datasource:
    url: jdbc:${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: validate

      show-sql: true

    flyway:
      enabled: true
      locations: classpath:db/migration


  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    root: INFO
    com.campusguardian.backend: DEBUG

pattern:
  console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

  api-docs:
    path: /v3/api-docs

jwt:
  secret: ZmQ3NGEwM2E4ZjZmNGQ2N2IwYmQ0YzYxZGUzZjQzYzNiZWM5N2Y0YjY5OTY2NTc5YjFlYzNkODVkNzNhNDUzYQ==
  access-token-expiration: 900000
  refresh-token-expiration: 604800000